# Generated by Django 4.1.7 on 2023-02-19 04:01

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("chat", "0003_alter_room_occupants"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="room",
            name="occupants",
        ),
        migrations.AddField(
            model_name="room",
            name="occupants",
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
    ]
