# Generated by Django 4.1.7 on 2023-03-12 05:58

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):
    dependencies = [
        ("chat", "0006_client"),
    ]

    operations = [
        migrations.AddField(
            model_name="client",
            name="connection_time",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
    ]
