# Generated by Django 4.1.7 on 2023-03-17 02:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("chat", "0008_alter_client_user"),
    ]

    operations = [
        migrations.AddField(
            model_name="client",
            name="connected",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="client",
            name="last_authed_message_time",
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name="client",
            name="user",
            field=models.OneToOneField(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
