# Generated by Django 4.1.7 on 2023-03-22 02:12

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("chat", "0009_client_connected_client_last_authed_message_time_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="gamepiece",
            name="board",
        ),
        migrations.RemoveField(
            model_name="gamepiece",
            name="owner",
        ),
        migrations.RemoveField(
            model_name="game",
            name="board",
        ),
        migrations.RemoveField(
            model_name="game",
            name="phase",
        ),
        migrations.RemoveField(
            model_name="game",
            name="turn",
        ),
        migrations.RemoveField(
            model_name="player",
            name="order",
        ),
        migrations.AddField(
            model_name="game",
            name="state",
            field=models.CharField(
                choices=[
                    ("waiting", "waiting"),
                    ("playing", "playing"),
                    ("finished", "finished"),
                ],
                default="waiting",
                max_length=255,
            ),
        ),
        migrations.DeleteModel(
            name="GameBoard",
        ),
        migrations.DeleteModel(
            name="GamePiece",
        ),
    ]
