# Generated by Django 4.1.7 on 2023-03-22 22:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("chat", "0010_remove_gamepiece_board_remove_gamepiece_owner_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="GameBoard",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("width", models.IntegerField()),
                ("height", models.IntegerField()),
            ],
        ),
        migrations.AddField(
            model_name="game",
            name="board",
            field=models.ForeignKey(
                default=None,
                on_delete=django.db.models.deletion.CASCADE,
                to="chat.gameboard",
            ),
            preserve_default=False,
        ),
    ]
