# Generated by Django 4.1.7 on 2023-03-22 22:38

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("chat", "0011_gameboard_game_board"),
    ]

    operations = [
        migrations.RenameField(
            model_name="gameboard",
            old_name="width",
            new_name="cols",
        ),
        migrations.RenameField(
            model_name="gameboard",
            old_name="height",
            new_name="rows",
        ),
    ]
