# Generated by Django 4.1.7 on 2023-03-23 00:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("chat", "0013_player_name_alter_player_user"),
    ]

    operations = [
        migrations.CreateModel(
            name="GamePiece",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("col", models.IntegerField()),
                ("row", models.IntegerField()),
                ("name", models.CharField(max_length=255)),
                (
                    "board",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="chat.gameboard"
                    ),
                ),
                (
                    "owner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="chat.player"
                    ),
                ),
            ],
        ),
    ]
