# Generated by Django 4.1.7 on 2023-05-08 22:42

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("chat", "0015_player_order"),
    ]

    operations = [
        migrations.AddField(
            model_name="gamepiece",
            name="class_name",
            field=models.CharField(default="brigand", max_length=255),
        ),
        migrations.AddField(
            model_name="gamepiece",
            name="movement",
            field=models.IntegerField(default=4),
        ),
    ]
